### ISSUE TITLE
Is there plan to implement sub-sampling in forwarder?

### ISSUE THREAD

**Issue by yhzhao** [signalfx/metricproxy#121]
E.g., if the incoming metric has a data rate of 10 data point per minute, when forwarding the metric to signalfx server, it does a down sample to 1 dps.

**Comment by mdubbyap** [comment]
Thanks for your question. Sorry for my late response. I'm a little confused by the units though. 10 data points per minute would be 1 every 6 seconds. You want the proxy to then artificially increase the sending frequency to 1 every second? Or did you mean 1 every minute? 

I guess it amounts to the same thing as we currently have no immediate plans to do either.  We have thought about pre-aggregation but it's not currently on the road map.

**Comment by mdubbyap** [comment]
Hi,
We haven't heard back from you regarding this issue in quite a while. At this time, we're marking this issue as Closed. However, if you're unsatisfied, please re-open.
