### ISSUE TITLE
readme typos

### ISSUE THREAD

**Issue by barbara-sfx** [signalfx/metricproxy#44]
-- Correct first sentence to:
The SignalFx Metricproxy lets you aggregate metrics and send them to SignalFx. 

--I believe this rewrite is accurate - the sentence as it stands is awkward/ambiguous:
We recommend placing the proxy either on the same server as another aggregator, such as statsd, or on a central server that is already receiving datapoints, such as graphite's carbon database.

-- In this sentence, either correct "not data" to "no data" or rewrite as shown:
correct: However, the service is limited in usefulness if there is ~~not~~ no data being sent to it. 
or rewrite: However, the service is limited in usefulness if no data is being sent to it.

**Comment by cep21** [comment]
"-- In this sentence, either correct "not data" to "no data" or rewrite as shown:"

Can you please quote where this is in the original?

**Comment by barbara-sfx** [comment]
I'm looking at this version: 

https://github.com/signalfx/metricproxy/blob/4004271bb8f3188f553c4626a43e54307b0c7387/README.md

which is the one that was linked to in the original email I received, listed as from Adam, subject "[metricproxy] Update format of README (#42)"

The sentence I'm referring to is under Requirements and Dependencies. 

Am I looking at the wrong version? It's newer than the one in Master but as I said, I'm a noob so could easily be in the wrong place.

**Comment by cep21** [comment]
Thanks for the help in fixing the docs!

When you say:

> In this sentence, either correct "not data" to "no data" or rewrite as shown

It's difficult to know what you're talking about since the document is very large.  It would save me a lot of time if you were very specific about what the before and after looked like.  Git pull requests are one way to be specific.  If not, then exact searchable text would be another way.

**Comment by barbara-sfx** [comment]
Please let me know where I am not being clear. I originally included the entire sentence, with "not" struck out and "no" in its place: 

- However, the service is limited in usefulness if there is ~~not~~ no data being sent to it. 

So you could search for any group of words in that sentence.

I then said the sentence is under the Requirements and Dependencies heading, so scrolling through the doc should make it easy to find.

Perhaps using git pull requests in the future would be easier overall...?

**Comment by cep21** [comment]
I see. I think you are correcting a version that's not currently in the master branch.

https://github.com/signalfx/metricproxy/blob/master/README.md
