### ISSUE TITLE
Conflicting configuration file location in readme versus dockerfile

### ISSUE THREAD

**Issue by jcsorvasi** [signalfx/metricproxy#46]
The dockerfile expects by default `/var/config/sfproxy/sfdbproxy.conf`, however the readme states:

> It assumes you will have a sfdbconfig.json file cross mounted to /var/config/sfproxy/sfdbconfig.json for the docker container.

The filenames are not the same which can be misleading.

**Comment by cep21** [comment]
Thanks for the ticket!  I modified the README.  Please let me know if you find anything else!
