### ISSUE TITLE
Please add support for Prometheus remote storage

### ISSUE THREAD

**Issue by salekseev** [signalfx/metricproxy#75]
An example could be found at: https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/example_write_adapter

**Comment by mdubbyap** [comment]
Thanks for the RFE. I'll talk with the team and see where this gets prioritized. Thanks again!

**Comment by mdubbyap** [comment]
I know you've found it, but for completeness https://github.com/signalfx/metricproxy/pull/76

**Comment by mdubbyap** [comment]
Closing. Thanks for the suggestion.
